title: Zhikang's Homepage
page-top-title: Zhikang Zhao
top-section-bg-text: Warm and moist as jade
home-subtitle: Zhikang Zhao&ensp;|&ensp;Pinocchio
copyright-text: '&copy; Zhikang Zhao 2023-2025. All Rights Reserved.'
